### ISSUE TITLE
[FE] Disable report payout option when a condition is resolved

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#458]
~~Once a Redeem position option is removed for a resolved condition in the list, it would be nice to remove it from a position details as well~~

EDIT:
The report payout option must be disabled if the condition was already resolved

**Comment by elena-zh** [comment]
According to the changes in #461, It would be nice not to Remove, just to disable redeem option for a resolved condition in a condition details and condition list pages.

**Comment by mariano-aguero** [comment]
@elena-zh I think this is already fixed, can you check it ?

**Comment by elena-zh** [comment]
@mariano-aguero , no, it is not fixed for a condition details page (that is why the issue is still in the Open status).
It is fixed for Conditions list.
Also, pls, take a look at my [comment ](https://github.com/gnosis/conditional-tokens-explorer/issues/458#issuecomment-709320346)above: it would be nice not to remove, but just to disable this action when a condition is already resolved.

**Comment by mariano-aguero** [comment]
> @mariano-aguero , no, it is not fixed for a condition details page (that is why the issue is still in the Open status).
> It is fixed for Conditions list.
> Also, pls, take a look at my [comment ](https://github.com/gnosis/conditional-tokens-explorer/issues/458#issuecomment-709320346)above: it would be nice not to remove, but just to disable this action when a condition is already resolved.

I updated the description of the issue, to take into account the option to be disabled is the report payout.
